name: beenai_sense
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  permission_handler: ^12.0.1
  flutter_tts: ^4.2.3
  camera: ^0.11.2
  http: ^1.5.0
  path_provider: ^2.1.5
  google_mlkit_text_recognition: ^0.15.0
  shared_preferences: ^2.2.2
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.8.0
  speech_to_text: 7.0.0
  url_launcher: ^6.1.7
  device_apps: ^2.2.0
  lottie: ^3.3.1
  tflite_flutter: ^0.11.0
  connectivity_plus: ^7.0.0
  internet_connection_checker_plus: ^2.9.0
  image: ^4.5.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/yolo11n_object365_float32.tflite
    - assets/labels.txt