name: beenai_sense
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  permission_handler: ^12.0.1
  flutter_tts: ^4.2.3
  camera: ^0.11.2
  http: ^1.4.0
  path_provider: ^2.1.5
  google_mlkit_text_recognition: ^0.15.0
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
  